# Generated by Django 4.1.7 on 2023-05-15 21:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_id", models.AutoField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=10)),
                ("emp_birth", models.DateField()),
                ("emp_gender", models.CharField(max_length=1)),
                ("emp_address", models.CharField(max_length=45)),
                ("emp_phone", models.CharField(max_length=45)),
                ("emp_account", models.CharField(max_length=45)),
                ("emp_plus", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Wage_hourly",
            fields=[
                ("wag_id", models.AutoField(primary_key=True, serialize=False)),
                ("wag_info", models.CharField(max_length=10)),
                ("wag_price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_pw",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedulefix",
            fields=[
                ("sch_id", models.AutoField(primary_key=True, serialize=False)),
                ("sch_date", models.DateField()),
                ("sch_start", models.DateTimeField()),
                ("sch_finish", models.DateTimeField()),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule_exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.employee",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        db_column="sch_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.schedulefix",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Absenteeism",
            fields=[
                ("abs_id", models.AutoField(primary_key=True, serialize=False)),
                ("abs_start", models.DateTimeField(auto_now_add=True)),
                ("abs_finish", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.employee",
                    ),
                ),
                (
                    "wageinfo",
                    models.ForeignKey(
                        db_column="wag_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.wage_hourly",
                    ),
                ),
            ],
        ),
    ]
