# Generated by Django 4.1.7 on 2023-05-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_absenteeism_abs_finish_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="absenteeism",
            name="abs_totalhour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="absenteeism",
            name="abs_totalwage",
            field=models.IntegerField(default=0),
        ),
    ]
