# Generated by Django 4.1.7 on 2023-05-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_remove_absenteeism_abs_totalhour"),
    ]

    operations = [
        migrations.AddField(
            model_name="absenteeism",
            name="abs_totalhour",
            field=models.IntegerField(default=0),
        ),
    ]
