# Generated by Django 4.1.7 on 2023-05-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_absenteeism_abs_totalhour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="absenteeism",
            old_name="abs_totalhour",
            new_name="abs_totalmin",
        ),
    ]
