# Generated by Django 4.1.7 on 2023-05-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_rename_abs_totalhour_absenteeism_abs_totalmin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="user_email",
        ),
    ]
