# Generated by Django 4.1.7 on 2023-05-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_timeinfo_remove_schedule_exchange_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                db_column="user_email",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="employee1",
            field=models.ForeignKey(
                db_column="emp_id1",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_employee1",
                to="management.employee",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="employee2",
            field=models.ForeignKey(
                db_column="emp_id2",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_employee2",
                to="management.employee",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="schedule1",
            field=models.ForeignKey(
                db_column="sch_id1",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_schedule1",
                to="management.schedulefix",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="schedule2",
            field=models.ForeignKey(
                db_column="sch_id2",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_schedule2",
                to="management.schedulefix",
            ),
            preserve_default=False,
        ),
    ]
