# Generated by Django 4.1.7 on 2023-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_alter_employee_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.AddField(
            model_name="employee",
            name="emp_email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="emp_level",
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
