# Generated by Django 4.1.7 on 2023-05-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0012_remove_employee_user_employee_emp_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("use_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
