# Generated by Django 4.1.7 on 2023-05-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0013_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
