# Generated by Django 4.1.7 on 2023-05-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0014_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("not_id", models.AutoField(primary_key=True, serialize=False)),
                ("not_title", models.CharField(max_length=50)),
                ("not_contents", models.CharField(max_length=200)),
                (
                    "employee_notice",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.employee",
                    ),
                ),
            ],
        ),
    ]
